//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsEntityLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalSold
    {
        public short ID { get; set; }
        public int ANIMAL_ID { get; set; }
        public int OWNER_ID { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
