//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsEntityLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public short ID { get; set; }
        public string NAME { get; set; }
        public int STOCKLEFT { get; set; }
        public double PRICE { get; set; }
        public double ITEM_PRICE { get; set; }
        public double MARKUP { get; set; }
        public double PRICE_TOMEET_MARK { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> TARGETSALEMK { get; set; }
    }
}
